version: 2.1

jobs:
  apply_sql_migrations:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install flyway cli
          command: |
            wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.24.0/flyway-commandline-10.24.0-linux-x64.tar.gz
            tar -xvf flyway-commandline-10.24.0-linux-x64.tar.gz
            sudo ln -s $(pwd)/flyway-10.24.0/flyway /usr/local/bin/flyway
            flyway -v
      - run:
          name: Apply SQL migrations
          command: |
             flyway -url="jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME" \
                -user="$DB_USERNAME" \
                -password="$DB_PASSWORD" \
                -locations=filesystem:sql-migrations \
                migrate
  test-backend:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: |
            npm install
      - run:
          name: Run backend tests
          command: |
            #npm test .

  build-backend-image:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_HUB_USERNAME: yahyeapps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend Docker image
          command: |
            docker build -t $DOCKER_HUB_USERNAME/storefront_backend:latest .

      - run:
          name: Push image to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            docker push $DOCKER_HUB_USERNAME/storefront_backend:latest
  deploy-and-verify:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install jq
          command: sudo apt-get update && sudo apt-get install -y jq
          
      - run:
          name: Deploy backend  and verify
          command: |
            echo "Triggering deployment..." 
            RESPONSE=$(curl -s -X POST \
              -H "Authorization: Bearer $SEVALLA_API_TOKEN" \
              -H "Content-Type: application/json" \
              "$SEVALLA_DEPLOY_HOOK_URL" \
              -d '{"docker_image":"'$DOCKER_HUB_USERNAME'/yahyeapps/storefront_backend:latest"}')

            DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r '.deployment.id')
            echo "Triggered deployment ID: $DEPLOYMENT_ID"
            echo "Verifying deployment status..."
            while true; do
                STATUS=$(curl -s -H "Authorization: Bearer $SEVALLA_API_TOKEN" \
                "https://api.sevalla.com/v2/applications/deployments/$DEPLOYMENT_ID" \
                | jq -r '.deployment.status')
              
              echo "Current deployment status: $STATUS"

              if [[ "$STATUS" == "success" ]]; then
                echo "✅ Deployment succeeded!"
                break
              elif [[ "$STATUS" == "failed" ]]; then
                echo "❌ Deployment failed!"
                exit 1
              fi

              echo "Waiting 10 seconds..."
              sleep 10
            done

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - apply_sql_migrations:
          context: shared_envs
          filters:
            branches:
              only: main
      - test-backend:
          context: shared_envs
          requires:
            - apply_sql_migrations
          filters:
            branches:
              only: main
      - build-backend-image:
          context: shared_envs
          requires:
            - test-backend
          filters:
            branches:
              only: main
      - deploy-and-verify:
          context: shared_envs
          requires:
            - build-backend-image
          filters:
            branches:
              only: main 
